import { lazy } from 'react'

const lazyTool = (loader, exportName) =>
  lazy(async () => {
    const module = await loader()
    return { default: module[exportName] }
  })

export const tools = [
  {
    slug: 'json-viewer',
    name: 'JSON Viewer & Formatter',
    description: 'Validate JSON, pretty-print it, minify it, and inspect a tree view.',
    keywords: ['json', 'formatter', 'viewer', 'tree'],
    category: 'Text / Data format',
    component: lazyTool(() => import('./JsonViewerTool'), 'JsonViewerTool'),
  },
  {
    slug: 'json-converter',
    name: 'JSON ↔ CSV / YAML Converter',
    description: 'Move between JSON, CSV, and YAML formats.',
    keywords: ['json', 'csv', 'yaml', 'convert'],
    category: 'Text / Data format',
    component: lazyTool(() => import('./JsonConvertTool'), 'JsonConvertTool'),
  },
  {
    slug: 'html-viewer',
    name: 'HTML Viewer',
    description: 'Render raw HTML inside a sandboxed preview.',
    keywords: ['html', 'viewer', 'preview'],
    category: 'Text / Data format',
    component: lazyTool(() => import('./HtmlViewerTool'), 'HtmlViewerTool'),
  },
  {
    slug: 'html-formatter',
    name: 'HTML Formatter / Beautifier / Minifier',
    description: 'Clean up or minify HTML markup.',
    keywords: ['html', 'formatter', 'beautify', 'minify'],
    category: 'Text / Data format',
    component: lazyTool(() => import('./HtmlFormatTool'), 'HtmlFormatTool'),
  },
  {
    slug: 'html-entities',
    name: 'HTML Parser / Entity Encoder-Decoder',
    description: 'Escape or unescape HTML entities.',
    keywords: ['html', 'entity', 'escape', 'unescape'],
    category: 'Text / Data format',
    component: lazyTool(() => import('./HtmlEntitiesTool'), 'HtmlEntitiesTool'),
  },
  {
    slug: 'markdown-previewer',
    name: 'Markdown Previewer',
    description: 'Preview markdown side-by-side with the source.',
    keywords: ['markdown', 'preview', 'md'],
    category: 'Text / Data format',
    component: lazyTool(() => import('./MarkdownTool'), 'MarkdownTool'),
  },
  {
    slug: 'url-parser',
    name: 'URL Parser',
    description: 'Inspect URL pieces and rebuild query strings.',
    keywords: ['url', 'query', 'params', 'parser'],
    category: 'URL / Web',
    component: lazyTool(() => import('./UrlParserTool'), 'UrlParserTool'),
  },
  {
    slug: 'url-codec',
    name: 'URL Encoder/Decoder',
    description: 'Encode and decode URL-safe text.',
    keywords: ['url', 'encode', 'decode'],
    category: 'URL / Web',
    component: lazyTool(() => import('./UrlCodecTool'), 'UrlCodecTool'),
  },
  {
    slug: 'base64',
    name: 'Base64 Encode/Decode',
    description: 'Handle base64 text plus file/image encoding.',
    keywords: ['base64', 'encode', 'decode', 'file'],
    category: 'URL / Web',
    component: lazyTool(() => import('./Base64Tool'), 'Base64Tool'),
  },
  {
    slug: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode JWT header, payload, and expiry.',
    keywords: ['jwt', 'token', 'auth'],
    category: 'Encoding / Hashing / IDs',
    component: lazyTool(() => import('./JwtTool'), 'JwtTool'),
  },
  {
    slug: 'hash-generator',
    name: 'Hash Generator',
    description: 'Create MD5, SHA-1, and SHA-256 hashes.',
    keywords: ['hash', 'md5', 'sha'],
    category: 'Encoding / Hashing / IDs',
    component: lazyTool(() => import('./HashTool'), 'HashTool'),
  },
  {
    slug: 'id-generator',
    name: 'UUID / ULID Generator',
    description: 'Generate modern client-side IDs.',
    keywords: ['uuid', 'ulid', 'id'],
    category: 'Encoding / Hashing / IDs',
    component: lazyTool(() => import('./IdTool'), 'IdTool'),
  },
  {
    slug: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert Unix epoch values and readable times.',
    keywords: ['timestamp', 'epoch', 'timezone'],
    category: 'Encoding / Hashing / IDs',
    component: lazyTool(() => import('./TimestampTool'), 'TimestampTool'),
  },
  {
    slug: 'diff-checker',
    name: 'Diff Checker',
    description: 'Compare text blocks inline or side by side.',
    keywords: ['diff', 'compare', 'text'],
    category: 'Text utilities',
    component: lazyTool(() => import('./DiffTool'), 'DiffTool'),
  },
  {
    slug: 'regex-tester',
    name: 'RegExp Tester',
    description: 'Test regex matches and capture groups live.',
    keywords: ['regex', 'regexp', 'pattern'],
    category: 'Text utilities',
    component: lazyTool(() => import('./RegexTool'), 'RegexTool'),
  },
  {
    slug: 'case-converter',
    name: 'Case Converter',
    description: 'Convert between common naming conventions.',
    keywords: ['case', 'camel', 'snake', 'kebab'],
    category: 'Text utilities',
    component: lazyTool(() => import('./CaseTool'), 'CaseTool'),
  },
  {
    slug: 'lorem-generator',
    name: 'Lorem Ipsum / Fake Data Generator',
    description: 'Create placeholder text or fake people records.',
    keywords: ['lorem', 'fake', 'data', 'generator'],
    category: 'Text utilities',
    component: lazyTool(() => import('./LoremTool'), 'LoremTool'),
  },
  {
    slug: 'color-picker',
    name: 'Color Picker/Converter',
    description: 'Convert color models and create a palette.',
    keywords: ['color', 'hex', 'rgb', 'hsl'],
    category: 'Misc',
    component: lazyTool(() => import('./ColorTool'), 'ColorTool'),
  },
  {
    slug: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes without any network calls.',
    keywords: ['qr', 'code', 'generator'],
    category: 'Misc',
    component: lazyTool(() => import('./QrTool'), 'QrTool'),
  },
]
